# Generated by Django 4.2.23 on 2025-09-01 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy peasy'), ('medium', 'Medium rare'), ('hard', 'Hard boiled')], max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Please enter the cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 minute.')])),
                ('ingredients', models.TextField(help_text="Enter ingredients with measurements,one per line, separated by a comma (e.g., '200g flour, '2tbsp sugar').")),
                ('method', models.TextField(help_text='Please enter each step on a new line.')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('heart_count_faves', models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
