# Generated by Django 4.2.23 on 2025-09-01 14:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='heart_count_faves',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
