# Generated by Django 4.2.23 on 2025-09-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_post', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipepost',
            options={'ordering': ['-created_on']},
        ),
    ]
